### ISSUE TITLE
Great idea!

### ISSUE THREAD

**Issue by prologic** [TomCrypto/lanius#1]
Oooh I love this; I'll try this and and get you some feedback of what works and what doesn't! Thanks for writing this!

**Comment by prologic** [comment]
Did a quick `pip install lanius` in my Python 2.7.10 environment and tried one of my project `README.md` files:

``` #!bash
$ lanius README.md 
Traceback (most recent call last):
  File "/home/prologic/bin/lanius", line 11, in <module>
    sys.exit(main())
  File "/home/prologic/lib/python2.7/site-packages/lanius/runner.py", line 88, in main
    run()
  File "/home/prologic/lib/python2.7/site-packages/lanius/runner.py", line 63, in run
    with fileinput.input(files=args.file) as f:
AttributeError: FileInput instance has no attribute '__exit__'

```

**Comment by TomCrypto** [comment]
Thanks!

Yes, I haven't added Python 2 support yet sorry. It shouldn't be too hard to make it compatible (I think it's just FileInput and some unicode encoding stuff). I'll work on Python 2 support soon, in the meantime it should work fine with Python 3 :)

**Comment by prologic** [comment]
Yes I recommend the use of [six](https://pypi.python.org/pypi/six) -- Also have a quick read of [Python 2/3 Unicode](https://gist.github.com/prologic/24cafc7315596b8683ca)

I can wait; it means I have to have a specially managed Python 3 environment just to run this :) (_development is fine_).

**Comment by TomCrypto** [comment]
Uh.. done. That was easier than I thought. I just hope the output will be fine, it seems to behave a bit wonky when piped into `less -R` (which _is_ the point after all) if I don't encode it as utf-8 in Python 2, it looks good in Python 3. So I have an if-else check in the runner for now, will have to standardise the encoding later on to make it work properly on both versions (`six` looks good for this, thanks)

(tested on 2.7 and 3.4)

**Comment by prologic** [comment]
Fantastic! Is this on a feature branch? Perhaps I can take a look and help :)

**Comment by TomCrypto** [comment]
It's straight on master at dc8576a76829b27dbbee740636702f31f0fa4a6a. As you can see there aren't many non-unicode-related compatibility issues thankfully, so it's just a matter of getting the encoding right. What I have now kind of works but breaks if the input markdown file contains unicode characters.

I have to say I have always been rather confused by how Python 2 handles unicode. I figured out I should use unicode escape characters like `\u00A7` inside theme.py rather than the actual symbol to avoid needing `#coding: utf8` at the top of the file, but I haven't yet been successful in using `six.u()` to correctly print the output in both Python 2 and Python 3 (including when stdout is redirected to a pipe). If you have time to take a look I'd definitely appreciate it.

I found the `sys.setdefaultencoding("utf-8")` hack for Python 2 which works but makes the tool quite slow to start..
